spring:
  application:
    name: ordens
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/ordens_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    mongodb:
      uri: mongodb://localhost:27017/ordens_audit_db
  batch:
    jdbc:
      initialize-schema: always
  jackson:
    serialization:
      write-dates-as-timestamps: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/corporate-realm
          jwk-set-uri: http://localhost:8080/realms/corporate-realm/protocol/openid-connect/certs

server:
  port: 8081